name: firstrepoPipe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-node-app .

    - name: Push Docker image
      run: docker push my-node-app

    - name: Deploy to server 
      run: echo "Deploying to server..."
