name: buildAndPushDockerImage

on:
  push:
    branches:
      - node.js

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
      
    - name: Login to Docker Hub
      uses: Docker/login-action@v1
      with:
        username: ${{ secrets.YOUR_DOCKER_USERNAME }}
        password: ${{ secrets.YOUR_DOCKER_PASSWORD }}

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t my-node-app .

    - name: Tag Docker image
      run: docker tag my-node-app:latest your_docker_username/my-node-app:latest

    - name: Push Docker image
      run: docker push your_docker_username/my-node-app:latest
